#!/bin/bash

SELF=$0
ALL_ARGS=$@

set -e


function check_rights {
    ROOT_UID=0
    if [ $UID != $ROOT_UID ]; then
        echo "This script needs administrator privileges."
        if [[ -t 1 ]]; then
            sudo "$SELF" $ALL_ARGS
        else
            exec 1>output_file
            gksu "$SELF" $ALL_ARGS
        fi
        exit
    fi
}

set -x 
check_rights

# prepare the chroot enviroment
if [ -z "$1" ]; then
    mount latest.img root
else
    mount latest.img root-ro
    mount -t aufs -o br="$1":root-ro none root
fi
mount --bind /dev/ root/dev

# prepare startup script for chroot
(
cat<<EOF
#!/bin/bash -x

declare -a PROG_LIST=("/sbin/initctl" "/usr/sbin/invoke-rc.d" "/usr/sbin/grub-probe")

function divert_programs() {
    for prog in "\${PROG_LIST[@]}"; do
        dpkg-divert --local --rename --add "\${prog}"
        ln -s /bin/true "\${prog}"
    done
}

function undivert_programs() {
    for prog in "\${PROG_LIST[@]}"; do
        rm "\${prog}"
        dpkg-divert --rename -remove "\${prog}"
    done
}

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts

export HOME=/root
export LC_ALL=C

# prepare for customization (running apt-get, for example)
dbus-uuidgen > /var/lib/dbus/machine-id

divert_programs

cd /root 
/bin/bash -i

# clean up
# !!!! warning !!!!
# the user is expected to call oem-config-prepare before exiting bash above.
# !!!!!!!!!!!!!!!!!

# don't do 'apt-get clean' as we may want to leave cached packages in
# don't do 'rm -rf /var/cache/apt/archives/*' for same reason above
rm -rf /tmp/* ~/.bash_history
rm /var/lib/dbus/machine-id

undivert_programs

umount /proc
mount | grep /proc > /dev/null
if [ $? -ne 0 ]; then
    umount -lf /proc
fi
umount /sys
umount /dev/pts
EOF
) > root/tmp/startup.sh
chmod +x root/tmp/startup.sh

# chroot
chroot root /tmp/startup.sh

umount root/dev
umount root

mount | grep root-ro > /dev/null
if [ $? -ne 0 ]; then
    umount root-ro
fi


