#!/bin/bash

SELF=$0
ALL_ARGS=$@

set -e


function check_rights {
    ROOT_UID=0
    if [ $UID != $ROOT_UID ]; then
        echo "This script needs administrator privileges."
        if [[ -t 1 ]]; then
            sudo "$SELF" $ALL_ARGS
        else
            exec 1>output_file
            gksu "$SELF" $ALL_ARGS
        fi
        exit
    fi
}

set -x 
check_rights

# prepare the chroot enviroment
mount latest.img root 
mount --bind /dev/ root/dev

# prepare startup script for chroot
(
cat<<EOF
#!/bin/bash -x
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts

export HOME=/root
export LC_ALL=C

# prepare for customization (running apt-get, for example)
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl
# for libpam-systemd workaround in chroot
dpkg-divert --local --rename --add /usr/sbin/invoke-rc.d
ln -s /bin/true /usr/sbin/invoke-rc.d

dpkg-divert --local --rename --add /usr/sbin/grub-probe
ln -s /bin/true /usr/sbin/grub-probe

cd /root 
/bin/bash -i

# clean up
# !!!! warning !!!!
# the user is expected to call oem-config-prepare before exiting bash above.
# !!!!!!!!!!!!!!!!!

# don't do 'apt-get clean' as we may want to leave cached packages in
# don't do 'rm -rf /var/cache/apt/archives/*' for same reason above
rm -rf /tmp/* ~/.bash_history
rm /var/lib/dbus/machine-id

rm /usr/sbin/grub-probe
dpkg-divert --rename --remove /usr/sbin/grub-probe

rm /usr/sbin/invoke-rc.d
dpkg-divert --rename --remove /usr/sbin/invoke-rc.d

rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl

umount /proc
mount | grep /proc > /dev/null
if [ $? -ne 0 ]; then
    umount -lf /proc
fi
umount /sys
umount /dev/pts
EOF
) > root/tmp/startup.sh
chmod +x root/tmp/startup.sh

# chroot
chroot root /tmp/startup.sh

umount root/dev
umount root




